# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Cspace < Formula
  desc "Portable CLI for managing Claude Code devcontainer instances"
  homepage "https://github.com/elliottregan/cspace"
  version "0.10.2"
  license "LicenseRef-PolyForm-Perimeter-1.0.0"

  depends_on "docker" => :optional

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/elliottregan/cspace/releases/download/v0.10.2/cspace_darwin_amd64.zip"
      sha256 "ca5b3389129a2c8a9b45592901c61c020402eadd783b7cb9873f03de15725703"

      define_method(:install) do
        bin.install "cspace"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/elliottregan/cspace/releases/download/v0.10.2/cspace_darwin_arm64.zip"
      sha256 "089b7ef675c4e835000b5a777b9405f3f88c9f3f01000014df3bad0e746b45e3"

      define_method(:install) do
        bin.install "cspace"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/elliottregan/cspace/releases/download/v0.10.2/cspace_linux_amd64.tar.gz"
      sha256 "c6f7e31cc381d0c42d73438943acd897df748107e8d854aba2dc9a4eed601547"
      define_method(:install) do
        bin.install "cspace"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/elliottregan/cspace/releases/download/v0.10.2/cspace_linux_arm64.tar.gz"
      sha256 "72f9b470a59844546626932161a5f06d85c15de3187c9735db770d8dfcd31cbb"
      define_method(:install) do
        bin.install "cspace"
      end
    end
  end

  test do
    system "#{bin}/cspace", "version"
  end
end
