# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class CspaceRc < Formula
  desc "cspace prerelease channel — for rc / beta testers"
  homepage "https://github.com/elliottregan/cspace"
  version "1.0.0-rc.11"
  license "LicenseRef-PolyForm-Perimeter-1.0.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/elliottregan/cspace/releases/download/v1.0.0-rc.11/cspace_darwin_amd64.zip"
      sha256 "7af5a1ef07afa87ddffd3c8f41d1040d418af0c8c3f3b0804a6e7a1eab44afeb"

      define_method(:install) do
        bin.install "cspace"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/elliottregan/cspace/releases/download/v1.0.0-rc.11/cspace_darwin_arm64.zip"
      sha256 "d51a69d27ec898567735c6fe0a821e4e2b432fa6ed3ae126b5cda8451a1d2418"

      define_method(:install) do
        bin.install "cspace"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/elliottregan/cspace/releases/download/v1.0.0-rc.11/cspace_linux_amd64.tar.gz"
      sha256 "376eafa4c0870e2ad73a63cf5705308d329a51e8f7af534d3a279a51c22cba79"
      define_method(:install) do
        bin.install "cspace"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/elliottregan/cspace/releases/download/v1.0.0-rc.11/cspace_linux_arm64.tar.gz"
      sha256 "2e349c4343bffef45ccfa8210ac135f28b4e77d016f4201c6025de14d3364787"
      define_method(:install) do
        bin.install "cspace"
      end
    end
  end

  conflicts_with "cspace", because: "both install `cspace`"

  test do
    system "#{bin}/cspace", "version"
  end
end
