# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class CspaceRc < Formula
  desc "cspace prerelease channel — for rc / beta testers"
  homepage "https://github.com/elliottregan/cspace"
  version "1.0.0-rc.8"
  license "LicenseRef-PolyForm-Perimeter-1.0.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/elliottregan/cspace/releases/download/v1.0.0-rc.8/cspace_darwin_amd64.zip"
      sha256 "dd5739e6eaa6380c626658760d5bf4b02d5b82fc032c07fca218908085c568e6"

      define_method(:install) do
        bin.install "cspace"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/elliottregan/cspace/releases/download/v1.0.0-rc.8/cspace_darwin_arm64.zip"
      sha256 "20c2f95eea291ebcea2c90bf7e503e268f23ce006c4be1c6209fb50f4030aa02"

      define_method(:install) do
        bin.install "cspace"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/elliottregan/cspace/releases/download/v1.0.0-rc.8/cspace_linux_amd64.tar.gz"
      sha256 "51561dc2471b5fe67a0a8bc759aa6b0f7c7858da9f6dc957b2d2404ac4476bcc"
      define_method(:install) do
        bin.install "cspace"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/elliottregan/cspace/releases/download/v1.0.0-rc.8/cspace_linux_arm64.tar.gz"
      sha256 "afa3d93fd93dbbaa2606db2b81688ad2bf2f3f58d0c308987d9c3ee957c813eb"
      define_method(:install) do
        bin.install "cspace"
      end
    end
  end

  conflicts_with "cspace", because: "both install `cspace`"

  test do
    system "#{bin}/cspace", "version"
  end
end
