# This file was generated by GoReleaser. DO NOT EDIT.
cask "cspace-rc" do
  version "1.0.0-rc.26"

  on_macos do
    on_intel do
      sha256 "78f32ac87969d484bf3204efb09d647e8f6a49740ff52f5fe1db3e4e47ef3126"
      url "https://github.com/elliottregan/cspace/releases/download/v#{version}/cspace_darwin_amd64.zip"
    end
    on_arm do
      sha256 "8d8539c9cb5d26c7c3b5cc91dee34605433de34658d04a2cea6904ea0062dc9b"
      url "https://github.com/elliottregan/cspace/releases/download/v#{version}/cspace_darwin_arm64.zip"
    end
  end

  on_linux do
    on_intel do
      sha256 "e7e0fa8addf5739491d067a42ba8e51c914692fbacb222730027999033a44617"
      url "https://github.com/elliottregan/cspace/releases/download/v#{version}/cspace_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "a4303bd65e1e7d4d34d0c002bc08ee332bc711ccccccdb8df3231532162400ab"
      url "https://github.com/elliottregan/cspace/releases/download/v#{version}/cspace_linux_arm64.tar.gz"
    end
  end

  name "cspace-rc"
  desc "cspace prerelease channel — for rc / beta testers"
  homepage "https://github.com/elliottregan/cspace"

  livecheck do
    skip "Auto-generated on release."
  end
  conflicts_with cask: [
      "cspace",
    ]

  binary "cspace"

  # No zap stanza required

end
