# This file was generated by GoReleaser. DO NOT EDIT.
cask "cspace-rc" do
  version "1.0.0-rc.43"

  on_macos do
    on_intel do
      sha256 "4e8d4758f1e67d095745be07752a79c853cc9f8c98cdc7bf33fc44b426f8bf16"
      url "https://github.com/elliottregan/cspace/releases/download/v#{version}/cspace_darwin_amd64.zip"
    end
    on_arm do
      sha256 "1e02e0fe42aa274719a2f33a20fa1c537c5cb83b88c151881e00e7d705c18e12"
      url "https://github.com/elliottregan/cspace/releases/download/v#{version}/cspace_darwin_arm64.zip"
    end
  end

  on_linux do
    on_intel do
      sha256 "384af00cd53a51a245eb1c9655dac17eb7b1febcdddc73838012af25a2748658"
      url "https://github.com/elliottregan/cspace/releases/download/v#{version}/cspace_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "b393c7a60fa42e7e5381e4ba880646c1491efa2b9862c5d064340f80ce0e9112"
      url "https://github.com/elliottregan/cspace/releases/download/v#{version}/cspace_linux_arm64.tar.gz"
    end
  end

  name "cspace-rc"
  desc "cspace prerelease channel — for rc / beta testers"
  homepage "https://github.com/elliottregan/cspace"

  livecheck do
    skip "Auto-generated on release."
  end
  conflicts_with cask: [
      "cspace",
    ]

  binary "cspace"

  postflight do
    system_command "/usr/bin/xattr",
                   args: ["-d", "com.apple.quarantine", "#{staged_path}/cspace"],
                   must_succeed: false
  end

  # No zap stanza required

end
