# This file was generated by GoReleaser. DO NOT EDIT.
cask "cspace-rc" do
  version "1.0.0-rc.51"

  on_macos do
    on_intel do
      sha256 "b859d273dccd78f12a0531fb96d0c7c5c550388d19398af22378a2846d9145eb"
      url "https://github.com/elliottregan/cspace/releases/download/v#{version}/cspace_darwin_amd64.zip"
    end
    on_arm do
      sha256 "02e7467bd0458ee97be72470a7f23fe1f95d4929510846b2dbb8487722717c38"
      url "https://github.com/elliottregan/cspace/releases/download/v#{version}/cspace_darwin_arm64.zip"
    end
  end

  on_linux do
    on_intel do
      sha256 "3f4edfce8c330e4dee3216664ea3795bcfe06a85462c1ca7bc8e1897c31f085c"
      url "https://github.com/elliottregan/cspace/releases/download/v#{version}/cspace_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "9b5293f05eb6f1626518a01080a75189902da11d38d8e93b31fff36dcd069690"
      url "https://github.com/elliottregan/cspace/releases/download/v#{version}/cspace_linux_arm64.tar.gz"
    end
  end

  name "cspace-rc"
  desc "cspace prerelease channel — for rc / beta testers"
  homepage "https://github.com/elliottregan/cspace"

  livecheck do
    skip "Auto-generated on release."
  end
  conflicts_with cask: [
      "cspace",
    ]

  binary "cspace"

  postflight do
    system_command "/usr/bin/xattr",
                   args: ["-d", "com.apple.quarantine", "#{staged_path}/cspace"],
                   must_succeed: false
  end

  # No zap stanza required

end
